// Version Vuejs/src/components/FeatureCard.vue
<template>
  <div class="card">
    <img v-bind:src="icon" v-bind:alt="title">
    <h2>{{ title }}</h2>
    <h3>{{ desc }}</h3>
  </div>
</template>

<script>
import config from "../../../src/utils/config.json";

export default {
  name: "FeatureCard",
  props: ["title", "icon", "desc"],
  data() {
    return {
      config: config
    };
  }
}
</script>

<style scoped>
  .card {
    width: 450px;
    height: 450px;
    background-color: #2F3136;
    border-radius: 1em;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin: 20px;
  }

  .card img {
    width: 100px;
    height: 100px;
  }

  .card h2 {
    margin-top: 20px;
  }

  .card h3 {
    margin-top: 20px;
  }

  .card:hover h2 {
    color: v-bind("config.infos.mainColor");
  }
</style>

// src/components/FeatureCard.tsx
import styles from "@/styles/components/FeatureCard.module.css"
import {useState} from "react";
import config from "@/utils/config.json"

interface FunctionCardProps {
    title: string
    description: string
    icon: string
}

export default function FeatureCard(props: FunctionCardProps) {
    const [hover, setHover] = useState(false)

    let style = {
        color: hover ? config.infos.mainColor : "white"
    }

    const handleMouseEnter = () => {
        setHover(true);
    };
    const handleMouseLeave = () => {
        setHover(false);
    };

    return (
        <>
            <div className={styles.card} onMouseEnter={handleMouseEnter} onMouseLeave={handleMouseLeave}>
                {
                    props.icon ? <img src={props.icon} alt={props.title}/> : null
                }
                <h2 className={styles.title} style={style}>{ props.title }</h2>
                {
                    props.description ? <h3>{ props.description }</h3> : null
                }
            </div>
        </>
    )
}
