// Version Vuejs/src/components/NavBar.vue
<template>
  <div class="navbar">
    <div class="left">
      <img v-bind:src="config.infos.avatar" v-bind:alt="config.infos.name" class="logo" />
      <button class="primary">Accueil</button>
      <button v-if="config.infos.docs" class="primary" v-on:click="redirect(config.infos.docs)">Documentation</button>
      <button v-if="config.infos.support" class="primary" v-on:click="redirect(config.infos.support)">Serveur support</button>
    </div>
    <div class="right">
      <router-link class="tertiary" to="/dash">Se connecter</router-link>
    </div>
  </div>
</template>

<script>
import config from "../../../src/utils/config.json";

export default {
  name: "NavBar",
  data() {
    return {
      config: config,
    };
  },
  methods: {
    redirect (link) {
      window.location.href = link;
    }
  }
}
</script>

<style scoped>
  .navbar {
    background: #2F3136;
    display: flex;
  }

  .navbar * {
    vertical-align: middle;
  }

  .navbar .left * {
    margin-left: 50px;
  }

  .navbar .left {
    margin: 10px;
  }

  .navbar .right * {
    margin: 20px;
    right: 0;
    position: absolute;
  }

  .logo {
    width: 100px;
    height: 100px;
    border-radius: 100%;
  }

  button.primary:hover {
    color: v-bind("config.infos.mainColor");
  }
</style>

// src/components/NavBar.tsx
import config from "@/utils/config.json"
import styles from "@/styles/components/NavBar.module.css"
import { Button } from "@/components/globals";

export default function NavBar() {
    return (
        <div className={styles.navbar}>
            <div className={styles.left}>
                <img src={config.infos.avatar} alt={config.infos.name} className={styles.logo}/>
                <Button label="Accueil" type="primary" redirect="/" />
                {
                    config.infos.docs ? <Button label="Documentation" type="primary" redirect={config.infos.docs}/> : null
                }
                {
                    config.infos.support ? <Button label="Serveur support" type="primary" redirect={config.infos.support} /> : null
                }
            </div>
            <div className={styles.right}>
                <Button label="Se connecter" type="tertiary" redirect="/login" />
            </div>
        </div>
    )
}
